Repository vtanja/UKS, pull requests merged in 2021-02, with the labels that each got.

#39 Refactor dashboard and profile
  uks/apps/issue/__init__.py
  uks/apps/issue/admin.py
  uks/apps/issue/apps.py
  uks/apps/issue/migrations/__init__.py
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/overview.html
  uks/apps/issue/tests.py
  uks/apps/issue/urls.py
  uks/apps/issue/views.py
  uks/apps/user/migrations/0001_initial.py
  uks/apps/user/models.py
  uks/apps/user/templates/home.html
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/templates/user/profile_info.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/uks/settings.py
  uks/uks/urls.py
Labels: refactor

#40 Refactor repostory overview
  uks/apps/repository/templates/repoDetail.html
  uks/apps/repository/urls.py
Labels: refactor

#41 Feature milestones overview
  requirements.txt
  uks/apps/milestone/__init__.py
  uks/apps/milestone/admin.py
  uks/apps/milestone/apps.py
  uks/apps/milestone/migrations/0001_initial.py
  uks/apps/milestone/migrations/__init__.py
  uks/apps/milestone/models.py
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/tests.py
  uks/apps/milestone/urls.py
  uks/apps/milestone/views.py
  uks/apps/repository/templates/repoDetail.html
  uks/apps/repository/urls.py
  uks/security/models.py
  uks/security/templates/base.html
  uks/uks/settings.py
Labels: feature

#43 Feature create new milestone
  uks/apps/milestone/forms.py
  uks/apps/milestone/migrations/0002_auto_20210204_2312.py
  uks/apps/milestone/models.py
  uks/apps/milestone/templates/milestone/milestone_create.html
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/urls.py
  uks/apps/milestone/views.py
Labels: feature

#45 Configuration github actions
  .github/workflows/build.yml
  .github/workflows/django-test.yml
  sonar-project.properties
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/views.py
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/uks/settings.py
Labels: configure

#46 Configuration nginx
  .gitignore
  config/nginx/nginx.conf
  docker-compose.yml
  start.sh
  uks/uks/settings.py
Labels: configure

#50 Bugfix configuration nginx
  config/nginx/nginx.conf
  docker-compose.yml
Labels: bug, configure

#47 Feature editing issues
  .github/workflows/build.yml
  .github/workflows/django-test.yml
  requirements.txt
  uks/apps/issue/admin.py
  uks/apps/issue/forms.py
  uks/apps/issue/migrations/0011_issue_labels.py
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/issue_detail.html
  uks/apps/issue/templates/issue/issue_form.html
  uks/apps/issue/templates/issue/issue_list.html
  uks/apps/issue/templates/issue/overview.html
  uks/apps/issue/tests/test_views.py
  uks/apps/issue/urls.py
  uks/apps/issue/views.py
  uks/apps/label/models.py
  uks/apps/migrations/__init__.py
  uks/apps/repository/templates/repoDetail.html
  uks/apps/user/templates/user/issue_list.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/views.py
  uks/uks/settings.py
Labels: feature, test

#51 Feature repository branches overview
  .github/workflows/build.yml
  uks/apps/branch/__init__.py
  uks/apps/branch/admin.py
  uks/apps/branch/apps.py
  uks/apps/branch/forms.py
  uks/apps/branch/migrations/0001_initial.py
  uks/apps/branch/migrations/0002_auto_20210205_1629.py
  uks/apps/branch/migrations/__init__.py
  uks/apps/branch/models.py
  uks/apps/branch/templates/branch/branch_detail.html
  uks/apps/branch/templates/branch/branch_list.html
  uks/apps/branch/tests.py
  uks/apps/branch/urls.py
  uks/apps/branch/views.py
  uks/apps/commit/__init__.py
  uks/apps/commit/admin.py
  uks/apps/commit/apps.py
  uks/apps/commit/migrations/__init__.py
  uks/apps/commit/models.py
  uks/apps/commit/tests.py
  uks/apps/commit/views.py
  uks/apps/issue/templates/issue/issue_detail.html
  uks/apps/issue/templates/issue/issue_form.html
  uks/apps/issue/templates/issue/issue_list.html
  uks/apps/label/templates/label_list.html
  uks/apps/milestone/templates/milestone/milestone_create.html
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/repository/forms.py
  uks/apps/repository/migrations/0002_repository_repo_url.py
  uks/apps/repository/migrations/0003_merge_20210209_1703.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repoDetail.html
  uks/apps/repository/templates/repository/overview.html
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/apps/user/migrations/0002_auto_20210210_1118.py
  uks/apps/user/models.py
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/templates/user/password_reset.html
  uks/apps/user/templates/user/password_reset_done.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/security/templates/base.html
  uks/uks/settings.py
Labels: feature

#52 Configuration actions
  .github/workflows/django-test.yml
  .github/workflows/scat.yml
Labels: configure

#55 Feature single milestone overview
  .github/workflows/django-test.yml
  uks/apps/milestone/models.py
  uks/apps/milestone/templates/milestone/milestone_detail.html
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/urls.py
  uks/apps/milestone/views.py
  uks/apps/user/models.py
Labels: feature

#56 Feature new label
  uks/apps/issue/views.py
  uks/apps/label/forms.py
  uks/apps/label/templates/label/create_label.html
  uks/apps/label/templates/label/delete_label.html
  uks/apps/label/templates/label/label_list.html
  uks/apps/label/urls.py
  uks/apps/label/views.py
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/views.py
Labels: feature

#60 Refactor after analysis
  uks/apps/branch/admin.py
  uks/apps/branch/views.py
  uks/apps/commit/admin.py
  uks/apps/commit/models.py
  uks/apps/commit/tests.py
  uks/apps/commit/views.py
  uks/apps/issue/views.py
  uks/apps/label/admin.py
  uks/apps/label/tests.py
  uks/apps/label/urls.py
  uks/apps/label/views.py
  uks/apps/repository/views.py
  uks/security/models.py
Labels: refactor

#54 Feature close issue
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/issue_detail.html
  uks/apps/issue/templates/issue/issue_list.html
  uks/apps/issue/tests/test_models.py
  uks/apps/issue/tests/test_views.py
  uks/apps/issue/urls.py
  uks/apps/issue/views.py
  uks/apps/repository/urls.py
  uks/apps/user/templates/user/issue_list.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/views.py
Labels: feature, test

#57 Feature wiki overview page
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/urls.py
  uks/apps/wiki/__init__.py
  uks/apps/wiki/admin.py
  uks/apps/wiki/apps.py
  uks/apps/wiki/migrations/0001_initial.py
  uks/apps/wiki/migrations/__init__.py
  uks/apps/wiki/models.py
  uks/apps/wiki/templates/wiki/wiki_detail.html
  uks/apps/wiki/templates/wiki/wiki_list.html
  uks/apps/wiki/urls.py
  uks/apps/wiki/views.py
  uks/uks/settings.py
Labels: feature

#63 Feature editing wiki page
  uks/apps/repository/models.py
  uks/apps/repository/views.py
  uks/apps/user/migrations/0001_initial.py
  uks/apps/user/migrations/0002_auto_20210210_1118.py
  uks/apps/user/migrations/0002_auto_20210213_0933.py
  uks/apps/user/models.py
  uks/apps/user/templates/home.html
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/apps/wiki/models.py
  uks/apps/wiki/templates/wiki/wiki_add.html
  uks/apps/wiki/templates/wiki/wiki_detail.html
  uks/apps/wiki/templates/wiki/wiki_form.html
  uks/apps/wiki/templates/wiki/wiki_history.html
  uks/apps/wiki/templates/wiki/wiki_list.html
  uks/apps/wiki/urls.py
  uks/apps/wiki/views.py
  uks/security/models.py
Labels: feature

#72 Refactor create edit issue
  .github/workflows/build.yml
  uks/apps/issue/forms.py
  uks/apps/issue/migrations/0013_auto_20210213_1024.py
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/issue_detail.html
  uks/apps/issue/templates/issue/issue_form.html
  uks/apps/issue/templates/issue/issue_list.html
  uks/apps/issue/tests/test_models.py
Labels: feature, refactor, test

#74 Feature edit, close and delete milestone
  uks/apps/milestone/models.py
  uks/apps/milestone/templates/milestone/milestone_delete.html
  uks/apps/milestone/templates/milestone/milestone_detail.html
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/templates/milestone/milestone_update.html
  uks/apps/milestone/urls.py
  uks/apps/milestone/views.py
  uks/apps/repository/urls.py
Labels: feature

#75 Add members to repository and delete members from repository
  uks/apps/label/views.py
  uks/apps/repository/forms.py
  uks/apps/repository/templates/repository/deleteCollaborators.html
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/templates/repository/repoSettings.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
Labels: feature

#80 Feature import commits
  requirements.txt
  uks/apps/branch/models.py
  uks/apps/commit/migrations/0001_initial.py
  uks/apps/commit/migrations/0002_auto_20210215_1412.py
  uks/apps/commit/migrations/0003_commit_branches.py
  uks/apps/commit/models.py
  uks/apps/issue/views.py
  uks/apps/repository/views.py
  uks/apps/wiki/views.py
Labels: enhancement, feature

#76 Fix displaying content
  uks/apps/branch/templates/branch/branch_list.html
  uks/apps/repository/migrations/0004_auto_20210215_1152.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/views.py
  uks/apps/user/templates/home.html
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/apps/wiki/templates/wiki/wiki_detail.html
  uks/apps/wiki/templates/wiki/wiki_form.html
  uks/apps/wiki/views.py
Labels: bug, enhancement, refactor

#82 Fix naming conventions
  uks/apps/repository/templates/repository/repoSettings.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
Labels: refactor

#83 Refactor issue change
  uks/apps/issue/admin.py
  uks/apps/issue/migrations/0014_delete_issuechange.py
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/issue_detail.html
  uks/apps/issue/tests/test_models.py
  uks/apps/issue/tests/test_views.py
  uks/apps/issue/views.py
  uks/apps/milestone/models.py
  uks/apps/project/models.py
  uks/apps/project/views.py
  uks/apps/repository/views.py
  uks/apps/user/migrations/0001_initial.py
  uks/apps/user/migrations/0002_auto_20210213_0933.py
  uks/apps/user/migrations/0003_historyitem_changed_issue.py
  uks/apps/user/models.py
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/views.py
  uks/apps/wiki/migrations/0003_wikihistoryitem.py
  uks/apps/wiki/views.py
Labels: refactor

#86 Refactor repository and wiki pages
  uks/apps/repository/migrations/0005_auto_20210215_2240.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/urls.py
  uks/apps/user/templates/user/dashboard.html
  uks/apps/wiki/templates/wiki/wiki_list.html
  uks/apps/wiki/views.py
Labels: refactor

#84 Repository edit and delete
  uks/apps/repository/forms.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repository/manageAccess.html
  uks/apps/repository/templates/repository/options.html
  uks/apps/repository/templates/repository/repoSettings.html
  uks/apps/repository/templates/repository/repoUpdate.html
  uks/apps/repository/templates/repository/repositoryDelete.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/apps/user/views.py
Labels: feature, refactor

#88 Refactor project and milestone apps
  uks/apps/milestone/templates/milestone/milestone_create.html
  uks/apps/milestone/templates/milestone/milestone_detail.html
  uks/apps/milestone/templates/milestone/milestone_list.html
  uks/apps/milestone/templates/milestone/milestone_update.html
  uks/apps/milestone/views.py
  uks/apps/project/templates/project/project_create.html
  uks/apps/project/templates/project/project_details.html
  uks/apps/project/templates/project/project_list.html
  uks/apps/project/templates/project/project_update.html
  uks/apps/project/views.py
Labels: enhancement, refactor

#87 Create, edit tag and tag overview page
  uks/apps/repository/templates/repository/overview.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/apps/tag/__init__.py
  uks/apps/tag/admin.py
  uks/apps/tag/apps.py
  uks/apps/tag/forms.py
  uks/apps/tag/migrations/0001_initial.py
  uks/apps/tag/migrations/0002_tag_commit.py
  uks/apps/tag/migrations/__init__.py
  uks/apps/tag/models.py
  uks/apps/tag/templates/tag/edit_tag.html
  uks/apps/tag/templates/tag/new_tag.html
  uks/apps/tag/templates/tag/tag_list.html
  uks/apps/tag/tests.py
  uks/apps/tag/urls.py
  uks/apps/tag/views.py
  uks/security/admin.py
  uks/uks/settings.py
Labels: feature

#90 Configure logging and monitoring
  .gitignore
  config/logstash/logstash.conf
  config/nginx/nginx.conf
  config/telegraf/telegraf.conf
  docker-compose.yml
  requirements.txt
  start.sh
  uks/apps/issue/tests/test_views.py
  uks/apps/issue/views.py
  uks/apps/repository/migrations/0006_auto_20210217_2229.py
  uks/apps/repository/models.py
  uks/apps/repository/views.py
  uks/apps/user/views.py
  uks/uks/settings.py
Labels: configure

#91 Feature single branch overview page
  uks/apps/branch/models.py
  uks/apps/branch/templates/branch/branch_detail.html
  uks/apps/branch/templates/branch/branch_list.html
  uks/apps/branch/urls.py
  uks/apps/branch/views.py
  uks/apps/commit/models.py
  uks/apps/repository/templates/repository/overview.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
Labels: feature

#89 Test projects
  .github/workflows/django-test.yml
  uks/apps/project/tests.py
  uks/apps/project/tests/__init__.py
  uks/apps/project/tests/test_models.py
  uks/apps/project/tests/test_views.py
Labels: test

#92 Label testing
  .github/workflows/django-test.yml
  uks/apps/label/tests/__init__.py
  uks/apps/label/tests/test_models.py
  uks/apps/label/tests/test_views.py
  uks/apps/tag/templates/tag/tag_list.html
Labels: test

#93 Feature issue statistics
  uks/apps/issue/migrations/0015_issue_date_created.py
  uks/apps/issue/models.py
  uks/apps/issue/templates/issue/issue_statistics.html
  uks/apps/issue/tests/test_views.py
  uks/apps/issue/views.py
  uks/apps/project/tests/test_models.py
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/templates/repository/repository_insights.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/security/templates/base.html
Labels: feature

#100 Fix limit access only collabs
  uks/apps/branch/templates/branch/branch_list.html
  uks/apps/branch/urls.py
  uks/apps/branch/views.py
  uks/apps/repository/models.py
  uks/apps/repository/urls.py
  uks/apps/user/templates/user/profile.html
  uks/apps/user/views.py
  uks/apps/wiki/templates/wiki/wiki_detail.html
  uks/apps/wiki/templates/wiki/wiki_history.html
  uks/apps/wiki/tests/test_views.py
  uks/apps/wiki/views.py
Labels: bug, enhancement

#104 repository search and change repository visibility
  uks/apps/repository/forms.py
  uks/apps/repository/migrations/0007_repository_visibility.py
  uks/apps/repository/migrations/0008_auto_20210219_1338.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repository/editVisibility.html
  uks/apps/repository/templates/repository/manageAccess.html
  uks/apps/repository/templates/repository/repoDetail.html
  uks/apps/repository/templates/repository/repoSettings.html
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/apps/user/templates/home.html
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/templates/user/search_results.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/security/templates/welcome.html
Labels: feature, refactor

#107 Create codecov.yml
  codecov.yml
Labels: configure

#108 Fix collaborators permissions
  uks/apps/branch/views.py
  uks/apps/insights/views.py
  uks/apps/issue/views.py
  uks/apps/label/views.py
  uks/apps/milestone/views.py
  uks/apps/project/templates/project/project_details.html
  uks/apps/project/tests/test_models.py
  uks/apps/project/tests/test_views.py
  uks/apps/project/views.py
  uks/apps/repository/models.py
  uks/apps/repository/views.py
  uks/apps/tag/views.py
  uks/apps/wiki/views.py
Labels: bug, refactor

#99 Configuration dockerhub deploy action
  .github/workflows/dockerhub-deploy.yml
  uks/uks/settings.py
Labels: configure

#110 Hotfix develop
  uks/apps/project/tests/test_views.py
  uks/apps/repository/views.py
  uks/apps/tag/migrations/0003_auto_20210219_1815.py
  uks/apps/tag/models.py
  uks/apps/tag/views.py
  uks/apps/wiki/views.py
Labels: bug, refactor

#111 Remove unused import
  uks/apps/tag/migrations/0003_auto_20210219_1815.py
Labels: refactor
