Repository vtanja/UKS, pull requests merged in 2021-01, with the labels that each got.

#28 Feature authentication
  .gitignore
  README.md
  requirements.txt
  uks/app/__init__.py
  uks/app/admin.py
  uks/app/apps.py
  uks/app/migrations/__init__.py
  uks/app/models.py
  uks/app/templates/base.html
  uks/app/tests.py
  uks/app/views.py
  uks/manage.py
  uks/security/__init__.py
  uks/security/admin.py
  uks/security/apps.py
  uks/security/forms.py
  uks/security/migrations/0001_initial.py
  uks/security/migrations/__init__.py
  uks/security/models.py
  uks/security/templates/security/login.html
  uks/security/templates/security/logout.html
  uks/security/templates/security/register.html
  uks/security/templates/welcome.html
  uks/security/tests.py
  uks/security/urls.py
  uks/security/views.py
  uks/uks/__init__.py
  uks/uks/asgi.py
  uks/uks/settings.py
  uks/uks/urls.py
  uks/uks/wsgi.py
Labels: feature

#30 Feature dashboard
  requirements.txt
  uks/app/urls.py
  uks/app/user/__init__.py
  uks/app/user/migrations/0001_initial.py
  uks/app/user/migrations/__init__.py
  uks/app/user/models.py
  uks/app/user/templates/home.html
  uks/app/user/templates/user/dashboard.html
  uks/app/user/templates/user/profile.html
  uks/app/user/urls.py
  uks/app/user/views.py
  uks/security/admin.py
  uks/security/migrations/0002_siteuser_repositories.py
  uks/security/models.py
  uks/uks/settings.py
  uks/uks/urls.py
Labels: feature

#32 Configuration docker
  .gitignore
  Dockerfile
  docker-compose.yml
  requirements.txt
  start.sh
  uks/uks/settings.py
  wait_for_postgres.sh
Labels: configure

#33 Feature user profile
  requirements.txt
  uks/app/user/forms.py
  uks/app/user/templates/home.html
  uks/app/user/templates/user/password_reset.html
  uks/app/user/templates/user/password_reset_complete.html
  uks/app/user/templates/user/password_reset_confirm.html
  uks/app/user/templates/user/password_reset_done.html
  uks/app/user/templates/user/profile.html
  uks/app/user/templates/user/profile_info.html
  uks/app/user/urls.py
  uks/app/user/views.py
  uks/security/migrations/0003_siteuser_profile_img.py
  uks/security/models.py
  uks/static/images/profile_default.png
  uks/uks/settings.py
  uks/uks/urls.py
Labels: feature

#36 Refactoring removing app folder
  uks/__init__.py
  uks/app/apps.py
  uks/app/models.py
  uks/app/repository/admin.py
  uks/app/repository/tests.py
  uks/app/urls.py
  uks/app/views.py
  uks/apps/__init__.py
  uks/apps/migrations/__init__.py
  uks/apps/repository/__init__.py
  uks/apps/repository/admin.py
  uks/apps/repository/apps.py
  uks/apps/repository/forms.py
  uks/apps/repository/migrations/0001_initial.py
  uks/apps/repository/migrations/__init__.py
  uks/apps/repository/models.py
  uks/apps/repository/templates/repoDetail.html
  uks/apps/repository/tests.py
  uks/apps/repository/urls.py
  uks/apps/repository/views.py
  uks/apps/user/__init__.py
  uks/apps/user/forms.py
  uks/apps/user/migrations/__init__.py
  uks/apps/user/models.py
  uks/apps/user/templates/home.html
  uks/apps/user/templates/user/dashboard.html
  uks/apps/user/templates/user/password_reset.html
  uks/apps/user/templates/user/password_reset_complete.html
  uks/apps/user/templates/user/password_reset_confirm.html
  uks/apps/user/templates/user/password_reset_done.html
  uks/apps/user/templates/user/profile.html
  uks/apps/user/templates/user/profile_info.html
  uks/apps/user/urls.py
  uks/apps/user/views.py
  uks/security/admin.py
  uks/security/models.py
  uks/security/templates/base.html
  uks/security/views.py
  uks/uks/settings.py
  uks/uks/urls.py
Labels: refactor
